Fixed bug found while negative testing
Negative test Failed
Program crashes when incorrect driverID is entered in body:
Error: Can't set headers after they are sent.

Caused by CustomerController Line 106&107 setting the status after other lines had set the status.

Fixed by adding a "hasSentError" boolean at the beginning of the function / making sure it is set to true when an error is created / making sure hasSentError is false before sending a status header